### PR TITLE
chore: update npm deps

### PR DESCRIPTION
**Pull request by rpl**
This PR (created on top of the changes from #11) includes updates for all the npm dependencies, plus some more tweaks to adapt config file and the content scripts to the updated dependencies (and enable modern js syntaxes for the eslint parser) and a small script to update the tippy resources bundled with the extensions from the tippy and popper npm package resources.

### CODE REVIEW

**Comment by rpl** [comment]
@marco-c I thought to also take a look into how much work was going to be updating the few dependencies included in the package.json file. I think we may also consider to move tippy into the dev dependencies given that in practice tippy's js and css bundles are packaged into the extension itself, wdyt?

**Comment by marco-c** [comment]
@rpl I put them in the `dependencies` section just because they are used in the addon itself and not only for building it, and I was thinking in the future we might do something smarter than just copying the files. I would be OK with moving them to `dev-dependencies` though, I don't have a strong preference.

Could you rebase the PR?

**Comment by rpl** [comment]
> @rpl I put them in the `dependencies` section just because they are used in the addon itself and not only for building it, and I was thinking in the future we might do something smarter than just copying the files. I would be OK with moving them to `dev-dependencies` though, I don't have a strong preference.

:+1: That was my guess, honestly it is not a big deal that it is listed in the dependencies, I just thought that moving it to a dev dependency may help to make it more immediately clear that, even if the tippy npm dependency is updated in package.json, to be actually be updated in the extension itself then the two related assets needs to be refreshed as well from the updated npm dependencies. 

Let's leave that as a separate followup to consider (in this particular PR I was mainly aiming to update the deps before proposing any new addition to dev dependency as part of introducing some unit or integration tests in the repo). 

> Could you rebase the PR?

Absolutely, I just rebased it and update this PR accordingly.

**Review by marco-c — APPROVED** [review]
Thanks!

**Pull request merged**
