### PR TITLE
Match Searchfox icon

### LINKED ISSUE #5: Use a nicer icon
The current one is **really** bad.

mozsearch-phabricator

### PR DESCRIPTION
**Pull request by nchevobbe**
Re-use searchfox icon, only changing the color to
the Phabricator header blue.

### CODE REVIEW

**Review by marco-c — APPROVED** [review]
Thanks!

**Comment by marco-c** [comment]
@nchevobbe when I load the addon in about:debugging, I see:
immagine

Is it working for you?

**Comment by marco-c** [comment]
Oh, I know what's up, the build script needs to be updated to copy the svg image instead of the png. I'll do that.

**Comment by nchevobbe** [comment]
Yes, it was showing up fine when adding the addon as a temporary addon

**Pull request merged**
